# Generated by Django 4.2.4 on 2023-09-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='about_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MF', 'Unset')], default='MF', max_length=2),
        ),
    ]
