# Generated by Django 4.2.4 on 2024-01-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post_pic.png', upload_to='post_pics'),
        ),
    ]
