on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      
        - name: Deploy on server
          uses: appleboy/scp-action@v0.1.3
          with:
            host: ${{ secrets.VPS_IP }}
            port: ${{ secrets.VPS_PORT }}
            username: root
            password: ${{ secrets.VPS_PASSWORD }}
            source: "./"
            target: ${{ secrets.VPS_WORK_DIR }}

