name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.vps_private }}
          REMOTE_HOST: ${{ secrets.vps_ip }}
          REMOTE_USER: root
          REMOTE_PORT: ${{ secrets.vps_port }}
          TARGET: ${{ secrets.REMOTE_TARGET }}


