on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      
        - name: Deploy on server
          uses: appleboy/scp-action@v0.1.3
          with:
            host: ${{ secrets.VPS_IP }}
            username: root
            password: ${{ secrets.VPS_PASSWORD }}
            source: "/home/runner/work/blog_project/.output"
            target: ${{ secrets.VPS_WORK_DIR }}

