name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: shimataro/ssh-key-action@v2
        env:
          key: ${{ secrets.VPS_PRIVATE }}
          known_hosts: ${{ secrets.VPS_IP }}
          REMOTE_USER: root
          REMOTE_PORT: ${{ secrets.VPS_PORT }}
          
      - name: Pull
        run: ssh root@194.33.105.155 "cd /home/root/projects/ & /usr/bin/git pull origin master"
            
