name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: actions/upload-artifact@v2
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_PRIVATE }}
          REMOTE_HOST: ${{ secrets.VPS_IP }}
          REMOTE_USER: root
          REMOTE_PORT: ${{ secrets.VPS_PORT }}
          server-dir: /home/root/project/
          script: |
            cd /home/root/project/
            git pull origin master
